sudo: required

language: node_js
node_js:
  - "8"

services:
  - mysql
  - rabbitmq
  - redis

env:
  MYSQL_URL=mysql://root@localhost:3306/user-store
  RABBITMQ_URL=amqp://guest:guest@localhost:5672
  REDIS_URL=redis://localhost:6379

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `user-store`;'
