sudo: required

language: node_js
node_js:
  - "8"

services:
  - mysql
  - rabbitmq

env:
  MYSQL_URL=mysql://root@localhost:3306/user-store
  RABBITMQ_URL=amqp://guest:guest@localhost:5672

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS "user-store";'
