version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"

  event-store:
    image: event-store
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "3000:3000"
    environment:
      MONGODB_URL: mongodb://mongo:27017/event-store
      RABBITMQ_URL: amqp://rabbitmq:5672
